data:
  raw_path: "data/raw/train.csv.zip"
  processed_path: "data/processed/dataset.csv"

model:
  save_path: "models/logistic_regression_model.pkl"
  vectorizer_path: "models/tfidf_vectorizer.pkl"

api:
  host: "0.0.0.0"
  port: 8000
